services:
  web:
    build: .
    ports:
      - mode: ingress
        target: 5000
        published: 5000
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:5000/"]
          interval: 30s
          timeout: 10s
          retries: 5
        environment:
          - PORT=5000
          - DATABASE_URL=${DATABASE_URL}  # external DB (like Supabase)
