services:
  web:
    build: .
    ports:
      - mode: ingress
        target: 5000
        published: 5000
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}  # external DB (like Supabase)
